### ISSUE TITLE
可以开发一个comfyui节点吗？

### ISSUE THREAD

**Issue by zouanhao** [KohakuBlueleaf/PixelOE#6]
可以开发一个comfyui节点吗？

**Comment by MakkiShizu** [comment]
> 可以开发一个comfyui节点吗？

Maybe you can try to use this?:
https://github.com/ltdrdata/ComfyUI-Manager/blob/main/custom-node-list.json#L9024
https://github.com/A4P7J1N7M05OT/ComfyUI-PixelOE-Wrapper
